SELECT * FROM SALES

SELECT CUSTOMERNAME, CITY, COUNTRY FROM SALES
WHERE STATUS = 'SHIPPED'

SELECT CUSTOMERNAME FROM SALES
WHERE CITY = 'NYC'

SELECT * FROM SALES
ORDER BY SALES DESC

SELECT TOP(3) CUSTOMERNAME, CITY, SUM(SALES) AS TOTAL_SALES FROM SALES
GROUP BY CUSTOMERNAME, CITY
ORDER BY TOTAL_SALES DESC

SELECT TOP(3) CUSTOMERNAME, CITY, AVG(SALES) AS AVG_SALES FROM SALES
GROUP BY CUSTOMERNAME, CITY
ORDER BY AVG_SALES DESC

SELECT DISTINCT CUSTOMERNAME FROM SALES

SELECT CUSTOMERNAME, CITY FROM SALES
WHERE YEAR_ID = '2003' OR  STATUS = 'SHIPPED'

SELECT CUSTOMERNAME, CITY FROM SALES
WHERE YEAR_ID = '2003' AND  STATUS = 'SHIPPED'

SELECT * FROM [Sales Data 2020]

SELECT * FROM [Sales Data 2021]

SELECT * FROM [Sales Data 2022]

-------*******------------UNION ALL---
SELECT * FROM [Sales Data 2020]
UNION ALL
SELECT * FROM [Sales Data 2021]
UNION ALL
SELECT * FROM [Sales Data 2022]

------UNION-------

SELECT * FROM [Sales Data 2020]
UNION
SELECT * FROM [Sales Data 2021]
UNION
SELECT * FROM [Sales Data 2022]

-------SUBQUERIES-----
SELECT * FROM SALES

SELECT CUSTOMERNAME, CITY FROM SALES
WHERE CUSTOMERNAME IN
( SELECT CUSTOMERNAME FROM SALES
        WHERE SALES > 10000)

-----DATE DIFFERENCE-----------------------

SELECT DATEDIFF(YEAR, '2021-02-07','2000-07-12')

SELECT DATEDIFF(DAY, '2021-02-07','2000-07-12')

SELECT DATEDIFF(MONTH, '2021-02-07','2000-07-12')


-----------HAVING-------
SELECT ORDERNUMBER, AVG(SALES) FROM SALES
GROUP BY ORDERNUMBER
HAVING AVG(SALES) > 1000
ORDER BY AVG(SALES) DESC

-----JOINS-----
SELECT * FROM [Sales Data 2020]
INNER JOIN [Sales Data 2021] ON [Sales Data 2020].ORDERNUMBER = [Sales Data 2021].OrderNumber
WHERE [Sales Data 2021].OrderNumber IS NOT NULL

SELECT * FROM [Sales Data 2020]
LEFT JOIN [Sales Data 2021] ON [Sales Data 2020].ORDERNUMBER = [Sales Data 2021].OrderNumber
WHERE [Sales Data 2021].OrderNumber IS NULL

SELECT * FROM [Sales Data 2020]
RIGHT JOIN [Sales Data 2021] ON [Sales Data 2020].ORDERNUMBER = [Sales Data 2021].OrderNumber
WHERE [Sales Data 2021].OrderNumber IS NOT NULL

SELECT * FROM SALES
ORDER BY SALES DESC, QUANTITYORDERED DESC 

----ROUNDING OFF--------------
SELECT ROUND(AVG(SALES), 2) AS AVG_SALES FROM SALES

SELECT COUNT(DISTINCT CUSTOMERNAME) FROM SALES

-------SUBQUERIES-----
SELECT * FROM SALES

SELECT DISTINCT CUSTOMERNAME FROM SALES

SELECT CUSTOMERNAME, CITY FROM SALES
WHERE CUSTOMERNAME IN
( SELECT CUSTOMERNAME FROM SALES
        WHERE SALES > 10000)

SELECT CAST(CUSTOMERNAME AS VARCHAR), CITY FROM SALES
WHERE QUANTITYORDERED IN
(SELECT CAST(CUSTOMERNAME AS VARCHAR) FROM SALES
   WHERE QUANTITYORDERED > 50)

SELECT CUSTOMERNAME, CITY FROM SALES
WHERE STATUS = 'SHIPPED'

SELECT ORDERNUMBER FROM [Sales Data 2020]
INTERSECT
SELECT ORDERQUANTITY FROM [Sales Data 2021]

SELECT * FROM SALES

--CREATING TABLE------------
 CREATE TABLE STATION2(
 ID INT PRIMARY KEY, 
 NAME VARCHAR(50) NOT NULL,
 AMOUNT INT NOT NULL CHECK(AMOUNT <> 0)
 );
 DELETE STATION

DROP TABLE STATION-------------DELETE TABLE FROM DATABASE

 DELETE STATION1
 DELETE STATION2

 CREATE TABLE STATION(
 ID INT PRIMARY KEY, 
 NAME VARCHAR(50) NOT NULL,
 AMOUNT INT NOT NULL CHECK(AMOUNT <> 0)
 );

 INSERT INTO STATION(ID,NAME, AMOUNT)
 VALUES(001, 'ALLAN', 25000),
        (002, 'ALEX', 20000),
        (003,  'RITAH', 15000),
        (004, 'LAWRENCE', 30000),
        (005, 'ARNOLD', 40000)

 SELECT * FROM STATION

 SELECT * FROM SALES

 SELECT CUSTOMERNAME, PRODUCTLINE, ROUND(AVG(SALES), 2) AS AVG_SALES FROM SALES
 GROUP BY CUSTOMERNAME, PRODUCTLINE
 ORDER BY AVG_SALES DESC

 SELECT * FROM SALES
 WHERE YEAR_ID = 2003 OR CITY = 'NYC'

 SELECT * FROM SALES
 WHERE YEAR_ID = 2003 AND CITY = 'NYC'

 -----TAXES OF 10$--EACH

 SELECT ORDERNUMBER, QUANTITYORDERED, PRICEEACH, SALES, STATUS,
 ROUND(SALES-10, 2) AS NET_SALES
 FROM SALES

 ------------TAXES OF 20$ FOR LESS THAN 50 UNITS--------
 SELECT ORDERNUMBER, QUANTITYORDERED, PRICEEACH, SALES, STATUS,
 ROUND(SALES-20, 2) AS NET_SALES
 FROM SALES
 WHERE QUANTITYORDERED <= 50

 ---RANGE-------------------
 SELECT * FROM SALES
 WHERE SALES > 5000 AND SALES < 20000

 ------IN---OPERATOR---
 SELECT * FROM SALES
 WHERE MONTH_ID IN(3,7)

 SELECT * FROM SALES 

 SELECT ORDERNUMBER,
 DAY(ORDERDATE) AS DAY_ORDERED,
 MONTH(ORDERDATE) AS MONTH_ORDERED
 FROM SALES

 ------BETWEEN--------AND------
 SELECT * FROM SALES
 WHERE SALES BETWEEN 3000 AND 5000

 SELECT * FROM PRODUCT

 SELECT * FROM RETURN_DATE

 SELECT * FROM PRODUCT_SUBCATEGORIES

 SELECT * FROM PRODUCT_CATEGORIES

SELECT PRODUCTNAME, MODELNAME, PRODUCTCOLOR, RETURNDATE, RETURNQUANTITY, TERRITORYKEY
FROM PRODUCT
JOIN RETURN_DATE ON PRODUCT.PRODUCTKEY = RETURN_DATE.PRODUCTKEY
WHERE TERRITORYKEY IS NOT NULL

------LEFT--JOIN-------

SELECT PRODUCTNAME, MODELNAME, PRODUCTCOLOR, RETURNDATE, RETURNQUANTITY, TERRITORYKEY
FROM PRODUCT
LEFT JOIN RETURN_DATE ON PRODUCT.PRODUCTKEY = RETURN_DATE.PRODUCTKEY
WHERE TERRITORYKEY IS NOT NULL

-------RIGHT JOIN-----------

SELECT PRODUCTNAME, MODELNAME, PRODUCTCOLOR, RETURNDATE, RETURNQUANTITY, TERRITORYKEY
FROM PRODUCT
RIGHT JOIN RETURN_DATE ON PRODUCT.PRODUCTKEY = RETURN_DATE.PRODUCTKEY
WHERE TERRITORYKEY IS NOT NULL

--------INNER JOIN-------------

SELECT PRODUCTNAME, MODELNAME, PRODUCTCOLOR, RETURNDATE, RETURNQUANTITY, TERRITORYKEY
FROM PRODUCT
INNER JOIN RETURN_DATE ON PRODUCT.PRODUCTKEY = RETURN_DATE.PRODUCTKEY
WHERE TERRITORYKEY IS NOT NULL

-------SECOND LATER GIVEN LETTER---------
SELECT * FROM SALES

SELECT CUSTOMERNAME FROM SALES
WHERE CUSTOMERNAME LIKE '_e%'

SELECT CUSTOMERNAME, ROUND(SUM(SALES),2) AS TOTAL_SALES
FROM SALES
WHERE CITY = 'NYC'
GROUP BY CUSTOMERNAME
ORDER BY TOTAL_SALES DESC

----------CONCAT------------------
SELECT *,
CONCAT(MONTH_ID, '-', YEAR_ID) AS FULL_DATE
FROM SALES

-----------INTERSECT---------
SELECT * FROM [Sales Data 2020]
INTERSECT
SELECT * FROM [Sales Data 2021]

SELECT QTR_ID, ROUND(SUM(SALES),2) AS TOTAL_SALES FROM SALES
GROUP BY QTR_ID
ORDER BY TOTAL_SALES DESC

SELECT QTR_ID, SUM(SALES) FROM SALES
GROUP BY QTR_ID
HAVING SUM(SALES) > 2000000

-----------------VIEWS-------
SELECT * FROM PRODUCT

SELECT * FROM PRODUCT_CATEGORIES

SELECT * FROM RETURN_DATE

SELECT * FROM PRODUCT_SUBCATEGORIES

CREATE VIEW PRODUCT_VIEW AS
SELECT PRODUCTNAME, MODELNAME, PRODUCTCOLOR, PRODUCTSIZE, PRODUCTCOST, PRODUCTPRICE,RETURNQUANTITY
FROM PRODUCT
JOIN RETURN_DATE ON PRODUCT.PRODUCTKEY = RETURN_DATE.PRODUCTKEY

SELECT * FROM PRODUCT_VIEW

SELECT MODELNAME, ROUND(SUM(PRODUCTPRICE),2) AS TOTAL_SALES FROM PRODUCT_VIEW
GROUP BY MODELNAME
ORDER BY TOTAL_SALES DESC

SELECT TOP 5 PRODUCTNAME, ROUND(SUM(PRODUCTPRICE),2) FROM PRODUCT_VIEW
GROUP BY PRODUCTNAME
HAVING ROUND(SUM(PRODUCTPRICE),2) > 10000
-------ALTERING VIEW----ADD PRODUCTSTYLE-------------
ALTER VIEW PRODUCT_VIEW AS
SELECT PRODUCTNAME, MODELNAME, PRODUCTCOLOR, PRODUCTSIZE, PRODUCTCOST, PRODUCTPRICE,PRODUCTSTYLE,RETURNQUANTITY
FROM PRODUCT
JOIN RETURN_DATE ON PRODUCT.PRODUCTKEY = RETURN_DATE.PRODUCTKEY

----------DROPPING VIEW--------------------
DROP VIEW PRODUCT_VIEW

----SUBQUERIES-------------------

SELECT * FROM SALES

SELECT AVG(SALES) FROM SALES

SELECT COUNT(ORDERNUMBER) FROM SALES
WHERE SALES > 3553.9

SELECT COUNT(ORDERNUMBER) FROM SALES
WHERE SALES >=
(SELECT AVG(SALES) FROM SALES)

SELECT PRODUCTLINE, CUSTOMERNAME, CITY FROM SALES
WHERE SALES >
(SELECT AVG(SALES) FROM SALES)

SELECT MIN(TOTAL) AS MIN_SALES,
MAX(TOTAL) AS MAX_SALES,
AVG(TOTAL) AS AVG_SALES
FROM
(SELECT CUSTOMERNAME, SUM(SALES) AS TOTAL FROM SALES GROUP BY CUSTOMERNAME) AS CUSTOMER_SALES;

------CORRELATED QUERIES OCCUR IN WHERE CLAUSE--------
SELECT CUSTOMERNAME, CITY, COUNTRY, PRODUCTLINE FROM SALES
WHERE SALES =
(SELECT MAX(SALES) FROM SALES)

SELECT CUSTOMERNAME FROM SALES
WHERE ORDERNUMBER NOT IN
(SELECT DISTINCT ORDERNUMBER FROM SALES)

CREATE DATABASE ALFRED;

USE ALFRED;

CREATE TABLE STATION(
 ID INT PRIMARY KEY, 
 NAME VARCHAR(50) NOT NULL,
 AMOUNT INT NOT NULL CHECK(AMOUNT <> 0)
 );

 INSERT INTO STATION(ID,NAME, AMOUNT)
 VALUES(001, 'ALLAN', 25000),
        (002, 'ALEX', 20000),
        (003,  'RITAH', 15000),
        (004, 'LAWRENCE', 30000),
        (005, 'ARNOLD', 40000)

EXEC sp_columns STATION-------------SHOW COLUMNS---------

 SELECT * FROM STATION

 INSERT INTO STATION
 VALUES(006, 'ALFRED', 60000)

 SELECT * FROM STATION

 SELECT * INTO ALFRED.dbo.STORES FROM SQL1.dbo.SALES;------------TRANSFERRING TABLES FROM ONE DATABASE TO ANOTHER

 SELECT * FROM STORES

----------------UPDATE TABLE-------------
 UPDATE STATION
 SET AMOUNT = 10000
 WHERE NAME = 'ALFRED'
 SELECT * FROM STATION

 DELETE FROM STATION
 WHERE NAME = 'ALEX'
 SELECT * FROM STATION


 USE ALFRED

SELECT * FROM MARKET_1
UNION ALL
SELECT * FROM MARKET_2
UNION ALL
SELECT * FROM MARKET_3

SELECT * FROM MARKET_1
UNION
SELECT * FROM MARKET_2
UNION
SELECT * FROM MARKET_3

SELECT * FROM CUSTOMER_DATA

SELECT DESCRIPTION, QUANTITY FROM CUSTOMER_DATA
WHERE PRICE BETWEEN 1 AND 5

SELECT DISTINCT DESCRIPTION, PRICE FROM CUSTOMER_DATA
ORDER BY PRICE DESC

SELECT SUM(PRICE) FROM CUSTOMER_DATA
WHERE INVOICE = '489447'

SELECT AVG(QUANTITY) FROM CUSTOMER_DATA

SELECT COUNTRY, COUNT(INVOICE) AS TOTAL_SALES FROM CUSTOMER_DATA
GROUP BY COUNTRY
ORDER BY TOTAL_SALES DESC

SELECT DESCRIPTION, SUM(QUANTITY) AS TOTAL_QUANTITY FROM CUSTOMER_DATA
GROUP BY DESCRIPTION
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT COUNTRY FROM CUSTOMER_DATA
WHERE DESCRIPTION = 'BAKING SET 9 PIECE RETROSPOT'
