SELECT * FROM [CO2_Dataset]
WHERE CO2_kt IS NULL

#REMOVINGANDUPDATING NULLS

UPDATE CO2_DATASET
SET CO2_kt = NULL
WHERE CO2_KT = 0

SELECT * FROM CO2_Dataset

-----TOP 10 POLLUTERS---------

SELECT TOP(10) COUNTRY_NAME, REGION, SUM(CO2_kt) AS CO2_TOTAL FROM CO2_DATASET
GROUP BY COUNTRY_NAME, REGION
ORDER BY CO2_TOTAL DESC

-----LEAST 10 POLLUTERS--------
SELECT TOP(10) COUNTRY_NAME, REGION, SUM(CO2_kt) AS CO2_TOTAL FROM CO2_DATASET
WHERE CO2_KT IS NOT NULL
GROUP BY COUNTRY_NAME, REGION
ORDER BY CO2_TOTAL ASC

----WORST YEAR AND BEST YEAR IN TERMS OF POLLUTION------
SELECT TOP(3) YEAR, SUM(CO2_KT) AS CO2_TOTAL FROM CO2_DATASET
WHERE CO2_KT IS NOT NULL
GROUP BY YEAR
ORDER BY CO2_TOTAL DESC


-----BEST YEAR WITH LEAST POLLUTION
SELECT TOP(3) YEAR, SUM(CO2_KT) AS CO2_TOTAL FROM CO2_DATASET
WHERE CO2_KT IS NOT NULL
GROUP BY YEAR
ORDER BY CO2_TOTAL ASC

-----TOP REGION POLLUTERS AND LEAST
SELECT DISTINCT REGION, SUM(CO2_KT) AS CO2_TOTAL FROM CO2_DATASET
WHERE CO2_KT IS NOT NULL
GROUP BY REGION
ORDER BY CO2_TOTAL DESC

-----COMPARING REGIONS AND COUNTRIES WITH CO2 FOOTPRINT

SELECT * FROM CO2_DATASET
WHERE COUNTRY_NAME = 'UGANDA'