SELECT * FROM MOVIE_DATA

----TOP BUDGETTED MOVIES AND LEAST BUDGET
SELECT TOP(10) MOVIE_TITLE, GENRE_1, SUM(BUDGET) AS TOPBUDGET FROM MOVIE_DATA
GROUP BY MOVIE_TITLE, GENRE_1
ORDER BY TOPBUDGET DESC

SELECT TOP(10) MOVIE_TITLE, GENRE_1, SUM(BUDGET) AS TOPBUDGET FROM MOVIE_DATA
GROUP BY MOVIE_TITLE, GENRE_1
ORDER BY TOPBUDGET ASC

-----HIGH AND LEAST BOX OFFICE REVENUE,(MOVIE AND GENRE)---ALTERNATE THE TWO BY DELETING ONE.
SELECT TOP(10) MOVIE_TITLE, GENRE_1, SUM(BOX_OFFICE_REVENUE) AS TOPREVENUE FROM MOVIE_DATA
GROUP BY MOVIE_TITLE, GENRE_1
ORDER BY TOPREVENUE DESC

SELECT TOP(10) MOVIE_TITLE, GENRE_1, SUM(BOX_OFFICE_REVENUE) AS TOPREVENUE FROM MOVIE_DATA
GROUP BY MOVIE_TITLE, GENRE_1
ORDER BY TOPREVENUE ASC

---TOP AND BOTTOM DIRECTORS AND ACTOR FOR MOVIES-----
SELECT TOP(3) DIRECTOR_1, COUNT(MOVIE_TITLE) AS TOPPEOPLE_D FROM MOVIE_DATA
GROUP BY DIRECTOR_1
ORDER BY TOPPEOPLE_D DESC

SELECT TOP(3) DIRECTOR_1, COUNT(MOVIE_TITLE) AS TOPPEOPLE_D FROM MOVIE_DATA
GROUP BY DIRECTOR_1
ORDER BY TOPPEOPLE_D ASC

SELECT TOP(3) CAST_1 , COUNT(MOVIE_TITLE) AS TOPPEOPLE_A FROM MOVIE_DATA
GROUP BY CAST_1
ORDER BY TOPPEOPLE_A DESC

SELECT TOP(3) CAST_1 , COUNT(MOVIE_TITLE) AS TOPPEOPLE_A FROM MOVIE_DATA
GROUP BY CAST_1
ORDER BY TOPPEOPLE_A ASC

------TOP AND BOTTOM DIRECTORS AND ACTORS FOR GENRES
SELECT TOP(3) DIRECTOR_1, COUNT(GENRE_1) AS TOPPEOPLE_D FROM MOVIE_DATA
GROUP BY DIRECTOR_1
ORDER BY TOPPEOPLE_D DESC

SELECT TOP(3) DIRECTOR_1, COUNT(GENRE_1) AS TOPPEOPLE_D FROM MOVIE_DATA
GROUP BY DIRECTOR_1
ORDER BY TOPPEOPLE_D ASC

SELECT TOP(3) CAST_1, COUNT(GENRE_1) AS TOPPEOPLE_A FROM MOVIE_DATA
GROUP BY CAST_1
ORDER BY TOPPEOPLE_A  DESC

SELECT TOP(3) CAST_1, COUNT(GENRE_1) AS TOPPEOPLE_A FROM MOVIE_DATA
GROUP BY CAST_1
ORDER BY TOPPEOPLE_A  ASC

-----EXTRACTING YEAR FROM
SELECT MOVIE_TITLE, GENRE_1, DIRECTOR_1, RELEASE_DATE, SUBSTRING(CAST (RELEASE_DATE,1,4) AS FLOAT) AS YEAR_ID
FROM MOVIE_DATA

-------HOLLYWOOD DATASET
SELECT * FROM HOLLYWOOD

-----TOP AND BOTTOM FILMS BY AUDIENCE SCORE
SELECT TOP(10) FILM, SUM(AUDIENCE_SCORE) AS AUDIENCE_VOTE FROM HOLLYWOOD
WHERE AUDIENCE_SCORE IS NOT NULL
GROUP BY FILM
ORDER BY AUDIENCE_VOTE DESC/ASC

-------TOP AND BOTTOM FILMS BY PROFITABILITY
SELECT TOP(10) FILM, SUM(PROFITABILITY) AS TOTAL_PROFIT FROM HOLLYWOOD
WHERE PROFITABILITY IS NOT NULL
GROUP BY FILM
ORDER BY TOTAL_PROFIT DESC/ASC

--------TOP AND BOTTOM FILMS ACCORDING ROTTEN-TOMATOES
SELECT TOP(10) FILM, SUM(ROTTEN_TOMATOES) AS ROTTEN_TOTAL FROM HOLLYWOOD
WHERE ROTTEN_TOMATOES IS NOT NULL
GROUP BY FILM
ORDER BY ROTTEN_TOTAL DESC/ASC

-------TOP AND BOTTOM FILMS BY WORLDWIDE_GROSS
SELECT TOP(10) FILM, SUM(WORLDWIDE_GROSS) AS WORLD_TOTAL FROM HOLLYWOOD
GROUP BY FILM
ORDER BY WORLD_TOTAL ASC

------NUMBER OF FILMS BY YEAR
SELECT YEAR, COUNT(FILM) AS YEAR_TOTAL FROM HOLLYWOOD
GROUP BY YEAR
ORDER BY YEAR_TOTAL DESC

------TOP GENRE BY NUMBER OF FILMS
SELECT DISTINCT GENRE, COUNT(FILM) AS GENRE_TOTAL FROM HOLLYWOOD
GROUP BY GENRE
ORDER BY GENRE_TOTAL DESC

----AVERAGE GENRE RATING BY AUDIENCE
SELECT DISTINCT GENRE, AVG(AUDIENCE_SCORE) AS AUDIENCE_VOTE FROM HOLLYWOOD
GROUP BY GENRE
ORDER BY AUDIENCE_VOTE DESC

-----AVERAGE GENRE PROFITABILITY 
SELECT DISTINCT GENRE, (PROFITABILITY) AS PROFIT FROM HOLLYWOOD
GROUP BY GENRE
ORDER BY PROFIT DESC


