SELECT * FROM NETFLIX_TITLES

SELECT * FROM NETFLIX_DIRECTORS

SELECT * FROM NETFLIX_COUNTRIES

SELECT * FROM NETFLIX_CATEGORY

SELECT * FROM NETFLIX_CAST

-----------JOINING TABLES----------
SELECT 
     NETFLIX_TITLES.*, DIRECTOR, COUNTRY, LISTED_IN, CAST

INTO NETFLIX

FROM NETFLIX_TITLES JOIN 

NETFLIX_DIRECTORS ON NETFLIX_TITLES.SHOW_ID = NETFLIX_DIRECTORS.SHOW_ID


JOIN NETFLIX_COUNTRIES ON NETFLIX_TITLES.SHOW_ID = NETFLIX_COUNTRIES.SHOW_ID

JOIN NETFLIX_CATEGORY ON NETFLIX_TITLES.SHOW_ID = NETFLIX_CATEGORY.SHOW_ID

JOIN NETFLIX_CAST ON NETFLIX_TITLES.SHOW_ID = NETFLIX_CAST.SHOW_ID


SELECT * FROM NETFLIX

SELECT DISTINCT SHOW_ID FROM NETFLIX

------MOST RELEASES IN A YEAR EVER----------
SELECT RELEASE_YEAR,  COUNT(DISTINCT SHOW_ID) AS TOTAL_RELEASES FROM NETFLIX
GROUP BY RELEASE_YEAR 
ORDER BY TOTAL_RELEASES DESC

------MOST MOVIE AND TV SHOWS RELEASES IN A YEAR EVER----------
SELECT RELEASE_YEAR,  COUNT(DISTINCT SHOW_ID) AS TOTAL_RELEASES FROM NETFLIX
WHERE TYPE = 'MOVIE'
GROUP BY RELEASE_YEAR 
ORDER BY TOTAL_RELEASES DESC

SELECT RELEASE_YEAR,  COUNT(DISTINCT SHOW_ID) AS TOTAL_RELEASES FROM NETFLIX
WHERE TYPE = 'TV SHOW'
GROUP BY RELEASE_YEAR 
ORDER BY TOTAL_RELEASES DESC

-------MOST GENRE RELEASED EVER------------
SELECT LISTED_IN,  COUNT(DISTINCT SHOW_ID) AS TOTAL_RELEASES FROM NETFLIX
GROUP BY LISTED_IN
ORDER BY TOTAL_RELEASES DESC

------LONGEST AND SHORTEST MOVIES EVER------------

SELECT MAX(DURATION_MINUTES) AS LONGEST_FILM, MIN(DURATION_MINUTES) AS SHORTEST_FILM FROM NETFLIX 

SELECT AVG(DURATION_MINUTES) AS AVERAGE_TIME FROM NETFLIX

SELECT DISTINCT TITLE, DESCRIPTION, TYPE, SUM( DISTINCT DURATION_MINUTES) AS TOTAL_MINUTES FROM NETFLIX
WHERE TYPE = 'MOVIE'
GROUP BY TITLE, DESCRIPTION, TYPE
ORDER BY TOTAL_MINUTES DESC

SELECT DISTINCT TITLE, DESCRIPTION, TYPE, SUM( DISTINCT DURATION_MINUTES) AS TOTAL_MINUTES FROM NETFLIX
WHERE TYPE = 'MOVIE'
GROUP BY TITLE, DESCRIPTION, TYPE
ORDER BY TOTAL_MINUTES ASC

-------LONGEST AND SHORTEST TV SHOWS---------
SELECT MAX(DURATION_SEASONS) AS LONGEST_SHOW, MIN(DURATION_SEASONS) AS SHORTEST_SHOW FROM NETFLIX

SELECT AVG(DURATION_SEASONS) AS AVERAGE_LENGTH FROM NETFLIX

SELECT DISTINCT TITLE, DESCRIPTION, TYPE, SUM( DISTINCT DURATION_SEASONS) AS TOTAL_SEASONS FROM NETFLIX
WHERE TYPE = 'TV SHOW'
GROUP BY TITLE, DESCRIPTION, TYPE
ORDER BY TOTAL_SEASONS DESC

SELECT DISTINCT TITLE, DESCRIPTION, TYPE, SUM( DISTINCT DURATION_SEASONS) AS TOTAL_SEASONS FROM NETFLIX
WHERE TYPE = 'TV SHOW'
GROUP BY TITLE, DESCRIPTION, TYPE
ORDER BY TOTAL_SEASONS ASC

-----FILM RATINGS------
SELECT DISTINCT RATING FROM NETFLIX

---------NUMBER OF RELEASES DEPENDING ON TV RAING------

SELECT DISTINCT RATING, COUNT(DISTINCT SHOW_ID) AS TOTAL_RELEASES FROM NETFLIX
GROUP BY RATING
ORDER BY TOTAL_RELEASES DESC

----------MOST RELEASES BY COUNTRY------------
SELECT DISTINCT COUNTRY, COUNT(DISTINCT SHOW_ID) AS TOTAL_RELEASES FROM NETFLIX
GROUP BY COUNTRY
ORDER BY TOTAL_RELEASES DESC

--------DIRECTOR OF MOST AND LEAST SHOWS-----------
SELECT TOP(10) DIRECTOR  , COUNT(DISTINCT SHOW_ID) AS TOTAL_RELEASES FROM NETFLIX
GROUP BY DIRECTOR
ORDER BY TOTAL_RELEASES DESC

SELECT TOP(10) DIRECTOR  , COUNT(DISTINCT SHOW_ID) AS TOTAL_RELEASES FROM NETFLIX
GROUP BY DIRECTOR
ORDER BY TOTAL_RELEASES ASC

-------CAST IN MOST AND LEAST SHOWS----------
SELECT TOP(10) CAST  , COUNT(DISTINCT SHOW_ID) AS TOTAL_RELEASES FROM NETFLIX
GROUP BY CAST
ORDER BY TOTAL_RELEASES DESC

SELECT TOP(10) CAST  , COUNT(DISTINCT SHOW_ID) AS TOTAL_RELEASES FROM NETFLIX
GROUP BY CAST
ORDER BY TOTAL_RELEASES ASC

----DIRECTOR JAN SUTER---------

----CAST HE WORKS WITH MOST---------
SELECT CAST, COUNT(DISTINCT SHOW_ID) AS TOTAL FROM NETFLIX
WHERE DIRECTOR = 'JAN SUTER'
GROUP BY CAST
ORDER BY TOTAL DESC

-----FILMS,TYPE OF FILMS, NUMBER OF FILMS AND GENRES----------
SELECT DISTINCT TITLE, RELEASE_YEAR, DURATION_MINUTES, DURATION_SEASONS, TYPE, LISTED_IN, DESCRIPTION FROM NETFLIX
WHERE DIRECTOR = 'JAN SUTER'

-------ANUPAM KHER------------

-------DIRECTOR HE WORKS FOR MOST---------
SELECT DIRECTOR, COUNT(DISTINCT SHOW_ID) AS TOTAL FROM NETFLIX
WHERE CAST = 'ANUPAM KHER'
GROUP BY DIRECTOR
ORDER BY TOTAL DESC

-----FILMS,TYPE OF FILMS, NUMBER OF FILMS AND GENRES----------
SELECT DISTINCT SHOW_ID , TITLE, RELEASE_YEAR, DURATION_MINUTES, DURATION_SEASONS, TYPE, LISTED_IN, DESCRIPTION FROM NETFLIX
WHERE CAST = 'ANUPAM KHER'

---------SHAH RUKH KHAN----------------
-------DIRECTOR HE WORKS FOR MOST---------
SELECT DIRECTOR, COUNT(DISTINCT SHOW_ID) AS TOTAL FROM NETFLIX
WHERE CAST = 'SHAH RUKH KHAN'
GROUP BY DIRECTOR
ORDER BY TOTAL DESC

-----FILMS,TYPE OF FILMS, NUMBER OF FILMS AND GENRES----------
SELECT DISTINCT SHOW_ID , TITLE, RELEASE_YEAR, DURATION_MINUTES, DURATION_SEASONS, TYPE, LISTED_IN, DESCRIPTION FROM NETFLIX
WHERE CAST = 'SHAH RUKH KHAN'

