SELECT * FROM AMAZON

---------TOTALS, AVERAGES, MAX AND MIN-----------
SELECT COUNT(DISTINCT NAME) AS BOOKS FROM AMAZON

SELECT COUNT(DISTINCT AUTHOR) AS AUTHORS FROM AMAZON

SELECT SUM(USER_RATING) AS TOTAL_RATING FROM AMAZON

SELECT AVG(USER_RATING) AS AVG_RATING FROM AMAZON

SELECT MAX(USER_RATING) AS HIGH_RATING FROM AMAZON

SELECT MIN(USER_RATING) AS LOW_RATING FROM AMAZON

SELECT SUM(REVIEWS) AS TOTAL_REVIEWS FROM AMAZON

SELECT AVG(REVIEWS) AS AVG_REVIEWS FROM AMAZON

SELECT MAX(REVIEWS) AS MAX_REVIEW FROM AMAZON

SELECT MIN(REVIEWS) AS MIN_REVIEW FROM AMAZON

SELECT SUM(PRICE) AS TOTAL_PRICE FROM AMAZON

SELECT AVG(PRICE) AS AVG_PRICE FROM AMAZON

SELECT MAX(PRICE) AS MAX_PRICE FROM AMAZON

SELECT MIN(PRICE) AS MIN_PRICE  FROM AMAZON

SELECT COUNT(DISTINCT YEAR) AS TOTAL_YEARS FROM AMAZON

SELECT COUNT(DISTINCT GENRE) AS TOTAL_GENRES FROM AMAZON

----------GROUPING DISTINCT CHARACTERS--------------

-----------NAMES OF BOOOKS----------------------
SELECT NAME,GENRE ,  COUNT(NAME) AS TOTAL_NAMES FROM AMAZON
GROUP BY NAME, GENRE
ORDER BY TOTAL_NAMES DESC

-----------AUTHOR-----------------------
SELECT DISTINCT AUTHOR,  COUNT(AUTHOR) AS TOTAL FROM AMAZON
GROUP BY AUTHOR
ORDER BY TOTAL DESC

--------------USER RATING------------------
SELECT USER_RATING,  COUNT(USER_RATING) AS TOTAL FROM AMAZON
GROUP BY USER_RATING
ORDER BY TOTAL DESC

---------------REVIEWS---------------------
SELECT REVIEWS,  COUNT(REVIEWS) AS TOTAL FROM AMAZON
GROUP BY REVIEWS 
ORDER BY TOTAL DESC

-----------------PRICE---------------------
SELECT PRICE,  COUNT(PRICE) AS TOTAL FROM AMAZON
GROUP BY PRICE
ORDER BY TOTAL DESC

---------------YEAR------------------------
SELECT YEAR,  COUNT(YEAR) AS TOTAL FROM AMAZON
GROUP BY YEAR
ORDER BY TOTAL DESC

-----------------GENRE----------------------
SELECT GENRE ,  COUNT(GENRE) AS TOTAL FROM AMAZON
GROUP BY GENRE
ORDER BY TOTAL DESC

----------------GENRE BY NAMES OF BOOKS--------------
SELECT GENRE ,COUNT(NAME) AS TOTAL FROM AMAZON
GROUP BY  GENRE
ORDER BY TOTAL DESC

--------------BOOKS MOST SOLD AND GENRE----------------
SELECT NAME,GENRE ,  COUNT(NAME) AS TOTAL_NAMES FROM AMAZON
GROUP BY NAME, GENRE
ORDER BY TOTAL_NAMES DESC

-------------GENRE BY RATING--------------
SELECT GENRE ,AVG(USER_RATING) AS AVG_RATING FROM AMAZON
GROUP BY  GENRE
ORDER BY AVG_RATING DESC

------------GENRE BY AUTHORS--------------------
SELECT GENRE ,COUNT(DISTINCT AUTHOR) AS TOTAL_AUTHORS FROM AMAZON
GROUP BY  GENRE
ORDER BY TOTAL_AUTHORS DESC

-------------GENRE BY REVIEWS-----------------
SELECT GENRE ,AVG(REVIEWS) AS AVG_REVIEWS FROM AMAZON
GROUP BY  GENRE
ORDER BY AVG_REVIEWS DESC

------------GENRE BY PRICE---------------------
SELECT GENRE ,AVG(PRICE) AS AVG_PRICE FROM AMAZON
GROUP BY  GENRE
ORDER BY AVG_PRICE DESC

------------YEAR BY GENRE----------------------
SELECT DISTINCT YEAR FROM AMAZON

-----------2009--------------------------
SELECT GENRE,COUNT(NAME) AS TOTAL FROM AMAZON
WHERE YEAR = '2009'
GROUP BY  GENRE
ORDER BY TOTAL DESC

-------------2012--------------------------
SELECT GENRE,COUNT(NAME) AS TOTAL FROM AMAZON
WHERE YEAR = '2012'
GROUP BY  GENRE
ORDER BY TOTAL DESC

------------2015-----------------------
SELECT GENRE,COUNT(NAME) AS TOTAL FROM AMAZON
WHERE YEAR = '2015'
GROUP BY  GENRE
ORDER BY TOTAL DESC

---------------2019----------------------
SELECT GENRE,COUNT(NAME) AS TOTAL FROM AMAZON
WHERE YEAR = '2019'
GROUP BY  GENRE
ORDER BY TOTAL DESC

-------------SCREENING TOP BOOKS-----------------
SELECT * FROM AMAZON
WHERE NAME LIKE 'Publication%' 

SELECT * FROM AMAZON
WHERE NAME LIKE 'The 5 %' 

























