SELECT * FROM AMAZON_PRODUCTS

SELECT * FROM AMAZON_CATEGORIES

---------DROP CERTAIN COLUMNS, RENAME AND MERGE TABLES------------
ALTER TABLE AMAZON_PRODUCTS
DROP COLUMN IMGURL, PRODUCTURL;

EXEC sp_rename 'AMAZON_CATEGORIES.ID', 'CATEGORY_ID', 'COLUMN';-------RENAMING ID COLUMN

SELECT AMAZON_PRODUCTS.*, CATEGORY_NAME
INTO AMAZON_BRAZIL
FROM AMAZON_PRODUCTS 
LEFT JOIN AMAZON_CATEGORIES ON AMAZON_PRODUCTS.CATEGORY_ID = AMAZON_CATEGORIES.CATEGORY_ID-------JOINING TABLES


SELECT TOP(1000) * FROM AMAZON_BRAZIL

--------TOTALS, MAXS, MINS, AVERAGES-----------
SELECT COUNT(DISTINCT ASIN) AS TOTAL FROM AMAZON_BRAZIL

SELECT COUNT(DISTINCT TITLE) AS TOTAL FROM AMAZON_BRAZIL

SELECT AVG(STARS) AS AVG_STARS FROM AMAZON_BRAZIL

SELECT MAX(STARS) AS MAX_STARS FROM AMAZON_BRAZIL

SELECT MIN(STARS) AS MIN_STARS FROM AMAZON_BRAZIL

SELECT AVG(REVIEWS) AS AVG_REVIEWS FROM AMAZON_BRAZIL

SELECT MAX(REVIEWS) AS MAX_REVIEWS FROM AMAZON_BRAZIL

SELECT MIN(REVIEWS) AS MIN_REVIEWS FROM AMAZON_BRAZIL

SELECT SUM(PRICE) AS TOTAL_PRICE FROM AMAZON_BRAZIL

SELECT AVG(PRICE) AS AVG_PRICE FROM AMAZON_BRAZIL

SELECT MAX(PRICE) AS MAX_PRICE FROM AMAZON_BRAZIL

SELECT MIN(PRICE) AS MIN_PRICE FROM AMAZON_BRAZIL

SELECT COUNT(DISTINCT CATEGORY_ID) AS TOTAL_CATEGORIES FROM AMAZON_BRAZIL

SELECT COUNT(DISTINCT ISBESTSELLER) AS TOTAL FROM AMAZON_BRAZIL

SELECT SUM(BOUGHTINLASTMONTH) AS TOTAL_PRICE FROM AMAZON_BRAZIL

SELECT AVG(BOUGHTINLASTMONTH) AS AVG_PRICE FROM AMAZON_BRAZIL

SELECT MAX(BOUGHTINLASTMONTH) AS MAX_PRICE FROM AMAZON_BRAZIL

SELECT MIN(BOUGHTINLASTMONTH) AS MIN_PRICE FROM AMAZON_BRAZIL

SELECT COUNT(DISTINCT CATEGORY_NAME) AS TOTAL FROM AMAZON_BRAZIL

----------------COMPARISONS-----------
---------PRODUCTS BOUGHT MOST-----------
SELECT TOP(10) TITLE, COUNT(TITLE) AS TOTAL FROM AMAZON_BRAZIL
GROUP BY TITLE
ORDER BY TOTAL DESC

----------PRODUCTS WITH MOST REVENUE----------
SELECT TOP(10) TITLE, SUM(PRICE) AS TOTAL FROM AMAZON_BRAZIL
GROUP BY TITLE
ORDER BY TOTAL DESC

-----------PRODUCTS MOST BOUGHT IN LAST MONTH----------
SELECT TOP(10) TITLE, SUM(BOUGHTINLASTMONTH) AS TOTAL FROM AMAZON_BRAZIL
GROUP BY TITLE
ORDER BY TOTAL DESC

-----------CATEGORY BOUGHT MOST-----------------
SELECT TOP(10) CATEGORY_NAME, COUNT(CATEGORY_NAME) AS TOTAL FROM AMAZON_BRAZIL
GROUP BY CATEGORY_NAME
ORDER BY TOTAL DESC

-----------CATEGORY BY AVG STARS--------------
SELECT TOP(10) CATEGORY_NAME, AVG(STARS) AS AVG_STARS FROM AMAZON_BRAZIL
GROUP BY CATEGORY_NAME
ORDER BY AVG_STARS DESC

-----------CATEGORY BY TOTAL PRICE---------------
SELECT TOP(10) CATEGORY_NAME, SUM(PRICE) AS TOTAL FROM AMAZON_BRAZIL
GROUP BY CATEGORY_NAME
ORDER BY TOTAL DESC

----------BESTSELLER STATS-------------
SELECT ISBESTSELLER, COUNT(ISBESTSELLER) AS TOTAL FROM AMAZON_BRAZIL
GROUP BY ISBESTSELLER
ORDER BY TOTAL DESC

---------PRODUCTS THAT ARE BEST SELLERS---------
SELECT DISTINCT TITLE, COUNT(TITLE) AS TOTAL FROM AMAZON_BRAZIL
WHERE ISBESTSELLER = 'TRUE'
GROUP BY TITLE
ORDER BY TOTAL DESC

--------CATEGORIES THAT ARE BEST SELLERS----------
SELECT DISTINCT TITLE,  CATEGORY_NAME FROM AMAZON_BRAZIL
WHERE ISBESTSELLER = 'TRUE'


--------------PRODUCTS WITH STARS ABOVE AVERGAE------------
SELECT TOP(10) (TITLE),STARS, COUNT(TITLE) AS TOTAL FROM AMAZON_BRAZIL
GROUP BY TITLE, STARS
HAVING STARS >= AVG(STARS)
ORDER BY TOTAL DESC

SELECT DISTINCT TITLE,STARS, COUNT(TITLE) AS TOTAL FROM AMAZON_BRAZIL
WHERE STARS >= 4.0
GROUP BY TITLE, STARS
ORDER BY TOTAL DESC

----------------PRODUCTS WHOSE REVIEWS ARE ABOVE AVERAGE-----------
SELECT TOP(10) (TITLE),REVIEWS, COUNT(TITLE) AS TOTAL FROM AMAZON_BRAZIL
GROUP BY TITLE, REVIEWS
HAVING REVIEWS >= 180
ORDER BY TOTAL DESC

SELECT DISTINCT TITLE,REVIEWS, COUNT(TITLE) AS TOTAL FROM AMAZON_BRAZIL
WHERE REVIEWS >= 180
GROUP BY TITLE, REVIEWS
ORDER BY TOTAL DESC

-----------PRODUCTS WHOSE PRICE IS ABOVE AVERAGE-----------------
SELECT TOP(10) (TITLE),PRICE, COUNT(TITLE) AS TOTAL FROM AMAZON_BRAZIL
GROUP BY TITLE, PRICE
HAVING PRICE>= 43.38
ORDER BY TOTAL DESC

SELECT DISTINCT TITLE,PRICE, COUNT(TITLE) AS TOTAL FROM AMAZON_BRAZIL
WHERE PRICE >= 43.38
GROUP BY TITLE, PRICE
ORDER BY TOTAL DESC







