SELECT * FROM NETFLIX_TITLES

-----------DEALING WITH DUPLICATE DATA-------------------
SELECT DISTINCT * FROM NETFLIX_TITLES

-----------MISSING DATA------------------------
SELECT * FROM NETFLIX_TITLES
WHERE TITLE IS NULL

------------TOTALS, MAXS, MINS AND AVERAGES-----------------
SELECT COUNT(DISTINCT SHOW_ID) FROM NETFLIX_TITLES

SELECT COUNT(DISTINCT TYPE) FROM NETFLIX_TITLES

SELECT COUNT(DISTINCT TITLE) FROM NETFLIX_TITLES

SELECT COUNT(DISTINCT DIRECTOR) FROM NETFLIX_TITLES

SELECT COUNT(DISTINCT COUNTRY) FROM NETFLIX_TITLES

SELECT COUNT(DISTINCT DATE_ADDED) FROM NETFLIX_TITLES

SELECT COUNT(DISTINCT RELEASE_YEAR) FROM NETFLIX_TITLES

SELECT COUNT(DISTINCT RATING) FROM NETFLIX_TITLES

SELECT COUNT(DISTINCT DURATION) FROM NETFLIX_TITLES

SELECT COUNT(DISTINCT LISTED_IN) FROM NETFLIX_TITLES

SELECT TYPE, COUNT(TYPE) AS TOTAL FROM NETFLIX_TITLES
GROUP BY TYPE
ORDER BY TOTAL DESC

SELECT DIRECTOR, COUNT(DIRECTOR) AS TOTAL FROM NETFLIX_TITLES
GROUP BY DIRECTOR
ORDER BY TOTAL DESC

SELECT COUNTRY,COUNT(COUNTRY) AS TOTAL FROM NETFLIX_TITLES
GROUP BY COUNTRY
ORDER BY TOTAL DESC

SELECT DATE_ADDED, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
GROUP BY DATE_ADDED
ORDER BY TOTAL DESC

SELECT RELEASE_YEAR, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
GROUP BY RELEASE_YEAR
ORDER BY TOTAL DESC

SELECT RATING, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
GROUP BY RATING
ORDER BY TOTAL DESC

SELECT DURATION, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
GROUP BY DURATION
ORDER BY TOTAL DESC

SELECT LISTED_IN, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
GROUP BY LISTED_IN
ORDER BY TOTAL DESC

--------------TV SHOWS----------------------
SELECT * FROM NETFLIX_TITLES
WHERE TYPE = 'TV SHOW'

SELECT DIRECTOR, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'TV SHOW'
GROUP BY DIRECTOR
ORDER BY TOTAL DESC

SELECT COUNTRY, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'TV SHOW'
GROUP BY COUNTRY
ORDER BY TOTAL DESC

SELECT DATE_ADDED, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'TV SHOW'
GROUP BY DATE_ADDED
ORDER BY TOTAL DESC

SELECT RELEASE_YEAR, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'TV SHOW'
GROUP BY RELEASE_YEAR
ORDER BY TOTAL DESC

SELECT RATING, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'TV SHOW'
GROUP BY RATING
ORDER BY TOTAL DESC

SELECT DURATION, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'TV SHOW'
GROUP BY DURATION
ORDER BY TOTAL DESC

SELECT LISTED_IN, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'TV SHOW'
GROUP BY LISTED_IN
ORDER BY TOTAL DESC

--------------MOVIES----------------------
SELECT * FROM NETFLIX_TITLES
WHERE TYPE = 'MOVIE'

SELECT DIRECTOR, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'MOVIE'
GROUP BY DIRECTOR
ORDER BY TOTAL DESC

SELECT COUNTRY, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'MOVIE'
GROUP BY COUNTRY
ORDER BY TOTAL DESC

SELECT DATE_ADDED, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'MOVIE'
GROUP BY DATE_ADDED
ORDER BY TOTAL DESC

SELECT RELEASE_YEAR, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'MOVIE'
GROUP BY RELEASE_YEAR
ORDER BY TOTAL DESC

SELECT RATING, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'MOVIE'
GROUP BY RATING
ORDER BY TOTAL DESC

SELECT DURATION, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'MOVIE'
GROUP BY DURATION
ORDER BY TOTAL DESC

SELECT LISTED_IN, COUNT(TITLE) AS TOTAL FROM NETFLIX_TITLES
WHERE TYPE = 'MOVIE'
GROUP BY LISTED_IN
ORDER BY TOTAL DESC



