-------------RESULTS DATASET---------------------
SELECT DISTINCT * FROM RESULTS

SELECT MAX(DATE) AS MAX_DATE, MIN(DATE) AS MIN_DATE FROM RESULTS

SELECT COUNT(DISTINCT HOME_TEAM) AS TOTAL_HOME, COUNT(DISTINCT AWAY_TEAM) AS TOTAL_AWAY FROM RESULTS

SELECT COUNT(DISTINCT HOME_SCORE) AS TOTAL_SCORES, MAX(HOME_SCORE) AS MAX_HOMESCORE, MIN(HOME_SCORE) AS MIN_HOMESCORE FROM RESULTS

SELECT COUNT(DISTINCT AWAY_SCORE) AS TOTAL_SCORES, MAX(AWAY_SCORE) AS MAX_AWAYSCORE, MIN(AWAY_SCORE) AS MIN_AWAYSCORE FROM RESULTS

SELECT SUM(HOME_SCORE) AS TOTAL_HOME, SUM(AWAY_SCORE) AS TOTAL_AWAY FROM RESULTS

SELECT COUNT(DISTINCT TOURNAMENT) AS TOTAL_TOURNAMENTS FROM RESULTS

SELECT COUNT(DISTINCT CITY) AS TOTAL_CITIES FROM RESULTS

SELECT COUNT(DISTINCT COUNTRY) AS TOTAL_COUNTRIES FROM RESULTS

SELECT COUNT(DISTINCT NEUTRAL) AS TOTAL FROM RESULTS

-----------NUMBER OF TOURNAMENTS-----------
SELECT TOURNAMENT, COUNT(TOURNAMENT) AS TOTAL FROM RESULTS
GROUP BY TOURNAMENT
ORDER BY TOTAL DESC

----------NUMBER OF GAMES BY DATE--------------
SELECT DATE, COUNT(DATE) AS TOTAL FROM RESULTS
GROUP BY DATE
ORDER BY TOTAL DESC

--------------NUMBER OF GAMES AS HOME_TEAM------------
SELECT HOME_TEAM, COUNT(HOME_TEAM) AS TOTAL FROM RESULTS
GROUP BY HOME_TEAM
ORDER BY TOTAL DESC

--------------NUMBER OF GAMES AS AWAY_TEAM---------------
SELECT AWAY_TEAM, COUNT(AWAY_TEAM) AS TOTAL FROM RESULTS
GROUP BY AWAY_TEAM
ORDER BY TOTAL DESC

-------------HOME SCORE BY NUMBER OF GAMES------------
SELECT HOME_SCORE, COUNT(HOME_SCORE) AS TOTAL FROM RESULTS
GROUP BY HOME_SCORE
ORDER BY TOTAL DESC

--------------AWAY SCORE BY NUMBER OF GAMES------------
SELECT AWAY_SCORE, COUNT(AWAY_SCORE) AS TOTAL FROM RESULTS
GROUP BY AWAY_SCORE
ORDER BY TOTAL DESC

----------------CITY BY NUMBER OF GAMES---------------
SELECT CITY, COUNT(CITY) AS TOTAL FROM RESULTS
GROUP BY CITY
ORDER BY TOTAL DESC

----------------COUNTRY BY NUMBER OF GAMES-----------------
SELECT COUNTRY, COUNT(COUNTRY) AS TOTAL FROM RESULTS
GROUP BY COUNTRY
ORDER BY TOTAL DESC

----------------NEUTRAL BY GAMES----------------------
SELECT NEUTRAL, COUNT(NEUTRAL) AS TOTAL FROM RESULTS
GROUP BY NEUTRAL
ORDER BY TOTAL DESC

----------------HIGH SCORING DATES( 5 OR MORE GOALS)------------
SELECT * FROM RESULTS
WHERE HOME_SCORE = '5' OR AWAY_SCORE = '5'

----------ALTERING TABLE ADDING TOTAL GOALS COLUMN----------
ALTER TABLE RESULTS
ADD TOTAL_SCORE AS (HOME_SCORE + AWAY_SCORE)

SELECT * FROM RESULTS

--------ALTERING TABLE TO ADD TEAM COMBINATIONS---------------
ALTER TABLE RESULTS
ADD FIXTURE AS (HOME_TEAM + AWAY_TEAM)

SELECT * FROM RESULTS

-------------DATE WHEN MORE GOALS ARE SCORED---------------
SELECT DATE, FIXTURE, TOURNAMENT, HOME_SCORE, AWAY_SCORE, SUM(TOTAL_SCORE) AS TOTAL FROM RESULTS
GROUP BY DATE, FIXTURE, TOURNAMENT, HOME_SCORE, AWAY_SCORE
ORDER BY TOTAL DESC

SELECT * FROM RESULTS
WHERE TOTAL_SCORE >= 20

---------FIXTURE PLAYED MOST----------------
SELECT FIXTURE, COUNT(FIXTURE) AS TOTAL FROM RESULTS
GROUP BY FIXTURE
ORDER BY TOTAL DESC

-------FIXTURE WITH MOST GOALS-----------
SELECT FIXTURE, SUM(TOTAL_SCORE) AS TOTAL FROM RESULTS
GROUP BY FIXTURE
ORDER BY TOTAL DESC

--------CITY IN WHICH MORE GAMES AND GOALS ARE SCORED----------
SELECT CITY, COUNT(CITY) AS TOTAL FROM RESULTS
GROUP BY CITY
ORDER BY TOTAL DESC

SELECT CITY,SUM(TOTAL_SCORE) AS TOTAL FROM RESULTS
GROUP BY CITY
ORDER BY TOTAL DESC

----------COUNTRY IN WHICH MORE GAMES AND GOALS ARE-----------
SELECT COUNTRY, COUNT(COUNTRY) AS TOTAL FROM RESULTS
GROUP BY COUNTRY
ORDER BY TOTAL DESC

SELECT COUNTRY, SUM(TOTAL_SCORE) AS TOTAL FROM RESULTS
GROUP BY COUNTRY
ORDER BY TOTAL DESC

---------TOURNAMENTS WITH MORE GAMES AND GOALS--------
SELECT TOURNAMENT, COUNT(TOURNAMENT) AS TOTAL FROM RESULTS
GROUP BY TOURNAMENT
ORDER BY TOTAL DESC

SELECT TOURNAMENT, SUM(TOTAL_SCORE) AS TOTAL FROM RESULTS
GROUP BY TOURNAMENT
ORDER BY TOTAL DESC













