SELECT * FROM POLICE_INCIDENTS

SELECT TOP(1000) * FROM POLICE_INCIDENTS
--------REMOVING UNNECESSARY COLUMNS---------
ALTER TABLE POLICE_INCIDENTS
DROP COLUMN INCIDENT_DATETIME, ROW_ID, CAD_NUMBER, CNN, SUPERVISOR_DISTRICT_2012, SUPERVISOR_DISTRICT, LATITUDE, LONGITUDE,POINT,
ESNCAG_BOUNDARY_FILE,CENTRAL_MARKET_TENDERLOIN_BOUNDARY_POLYGON_UPDATED, CIVIC_CENTER_HARM_REDUCTION_PROJECT_BOUNDARY,
HSOC_ZONES_AS_OF_2018_06_05;

SELECT * FROM POLICE_INCIDENTS

-------TOTALS, MAXS, MINS, AVERAGES------------
SELECT COUNT(DISTINCT INCIDENT_ID) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT INCIDENT_NUMBER) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT INCIDENT_CODE) AS TOTAL_INCIDENT_CODES FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT INCIDENT_DATE) AS TOTAL_DAYS FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT INCIDENT_YEAR) AS TOTAL_YEARS FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT REPORT_TYPE_CODE) AS TOTAL_REPORT_TYPE_CODES FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT REPORT_TYPE_DESCRIPTION) AS TOTAL_REPORT_TYPE FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT INCIDENT_CATEGORY) AS TOTAL_INCIDENTCATEGORIES FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT INCIDENT_SUBCATEGORY) AS TOTAL_INCIDENTSUBCATEGORIES FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT INCIDENT_DESCRIPTION) AS TOTAL_INCIDENT_DESCRIPTIONS FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT RESOLUTION) AS TOTAL_RESOLUTIONS FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT INTERSECTION) AS TOTAL_INTERSECTIONS FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT POLICE_DISTRICT) AS TOTAL_POLICEDISTRICTS FROM POLICE_INCIDENTS

SELECT COUNT(DISTINCT ANALYSIS_NEIGHBORHOOD) AS TOTAL_ANALYSISNEIGHBORHOODS FROM POLICE_INCIDENTS

------------COMPARISON OF DIFFERENT FACTORS------------

-------------INCIDENT_DATE-----------------------------
SELECT DISTINCT INCIDENT_DATE, COUNT(INCIDENT_DATE) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY INCIDENT_DATE
ORDER BY TOTAL_INCIDENTS DESC

-------------INCIDENT_TIME-----------------------------
SELECT DISTINCT INCIDENT_TIME, COUNT(INCIDENT_TIME) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY INCIDENT_TIME
ORDER BY TOTAL_INCIDENTS DESC

---------------INCIDENT_YEAR----------------------------
SELECT DISTINCT INCIDENT_YEAR, COUNT(INCIDENT_YEAR) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY INCIDENT_YEAR
ORDER BY TOTAL_INCIDENTS DESC

---------------INCIDENT_DAY_OF_WEEK----------------------
SELECT DISTINCT INCIDENT_DAY_OF_WEEK, COUNT(INCIDENT_DAY_OF_WEEK) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY INCIDENT_DAY_OF_WEEK
ORDER BY TOTAL_INCIDENTS DESC

--------------REPORT TYPE CODE-------------------------
SELECT DISTINCT REPORT_TYPE_CODE, COUNT(REPORT_TYPE_CODE) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY REPORT_TYPE_CODE
ORDER BY TOTAL_INCIDENTS DESC

-------------REPORT_TYPE-DESCRIPTION--------------------
SELECT DISTINCT REPORT_TYPE_DESCRIPTION, COUNT(REPORT_TYPE_DESCRIPTION) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY REPORT_TYPE_DESCRIPTION
ORDER BY TOTAL_INCIDENTS DESC

--------------INCIDENT CATEGORY------------------------
SELECT DISTINCT INCIDENT_CATEGORY, COUNT(INCIDENT_CATEGORY) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY INCIDENT_CATEGORY
ORDER BY TOTAL_INCIDENTS DESC

----------------INCIDENT SUBCATEGORY---------------------
SELECT DISTINCT INCIDENT_SUBCATEGORY, COUNT(INCIDENT_SUBCATEGORY) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY INCIDENT_SUBCATEGORY
ORDER BY TOTAL_INCIDENTS DESC

-----------------INCIDENT DESCRIPTION-----------------------
SELECT DISTINCT INCIDENT_DESCRIPTION, COUNT(INCIDENT_DESCRIPTION) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY INCIDENT_DESCRIPTION
ORDER BY TOTAL_INCIDENTS DESC

----------------RESOLUTION-----------------------------------
SELECT DISTINCT RESOLUTION, COUNT(RESOLUTION) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY RESOLUTION
ORDER BY TOTAL_INCIDENTS DESC

------------------INTERSECTION----------------------------
SELECT DISTINCT INTERSECTION, COUNT(INTERSECTION) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY INTERSECTION
ORDER BY TOTAL_INCIDENTS DESC

-------------------POLICE DISTRICT---------------------
SELECT DISTINCT POLICE_DISTRICT, COUNT(POLICE_DISTRICT) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY POLICE_DISTRICT
ORDER BY TOTAL_INCIDENTS DESC

-------------------ANALYSIS NEIGHBORHOOD-------------------
SELECT DISTINCT ANALYSIS_NEIGHBORHOOD, COUNT(ANALYSIS_NEIGHBORHOOD) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY ANALYSIS_NEIGHBORHOOD
ORDER BY TOTAL_INCIDENTS DESC

-------------------NEIGHBORHOODS----------------------------
SELECT DISTINCT NEIGHBORHOODS, COUNT(NEIGHBORHOODS) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY NEIGHBORHOODS
ORDER BY TOTAL_INCIDENTS DESC

------------------CURRENT SUPERVISOR DISTRICTS-------------------
SELECT DISTINCT CURRENT_SUPERVISOR_DISTRICTS, COUNT(CURRENT_SUPERVISOR_DISTRICTS) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY CURRENT_SUPERVISOR_DISTRICTS
ORDER BY TOTAL_INCIDENTS DESC

----------------CURRENT_POLICE_DISTRICTS-------------------------
SELECT DISTINCT CURRENT_POLICE_DISTRICTS, COUNT(CURRENT_POLICE_DISTRICTS) AS TOTAL_INCIDENTS FROM POLICE_INCIDENTS
GROUP BY CURRENT_POLICE_DISTRICTS
ORDER BY TOTAL_INCIDENTS DESC

-----------------INVESTIGATING CERTAIN INCIDENTS-------------------------

---------------YEAR, DAY AND TIME IN WHICH LARCENCY OCCURED MOST--------------
SELECT INCIDENT_YEAR, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'LARCENY THEFT'
GROUP BY INCIDENT_YEAR
ORDER BY TOTAL DESC

SELECT INCIDENT_DATE, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'LARCENY THEFT'
GROUP BY INCIDENT_DATE
ORDER BY TOTAL DESC

SELECT INCIDENT_TIME, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'LARCENY THEFT'
GROUP BY INCIDENT_TIME
ORDER BY TOTAL DESC

SELECT INCIDENT_DAY_OF_WEEK, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'LARCENY THEFT'
GROUP BY INCIDENT_DAY_OF_WEEK
ORDER BY TOTAL DESC

---------------YEAR, DAY AND TIME IN WHICH BURGLARY OCCURED MOST--------------
SELECT INCIDENT_YEAR, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'BURGLARY'
GROUP BY INCIDENT_YEAR
ORDER BY TOTAL DESC

SELECT INCIDENT_DATE, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'BURGLARY'
GROUP BY INCIDENT_DATE
ORDER BY TOTAL DESC

SELECT INCIDENT_TIME, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'BURGLARY'
GROUP BY INCIDENT_TIME
ORDER BY TOTAL DESC

SELECT INCIDENT_DAY_OF_WEEK, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'BURGLARY'
GROUP BY INCIDENT_DAY_OF_WEEK
ORDER BY TOTAL DESC

---------------YEAR, DAY AND TIME IN WHICH ASSAULT OCCURED MOST--------------
SELECT INCIDENT_YEAR, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'ASSAULT'
GROUP BY INCIDENT_YEAR
ORDER BY TOTAL DESC

SELECT INCIDENT_DATE, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'ASSAULT'
GROUP BY INCIDENT_DATE
ORDER BY TOTAL DESC

SELECT INCIDENT_TIME, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'ASSAULT'
GROUP BY INCIDENT_TIME
ORDER BY TOTAL DESC

SELECT INCIDENT_DAY_OF_WEEK, COUNT(INCIDENT_CATEGORY) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_CATEGORY = 'ASSAULT'
GROUP BY INCIDENT_DAY_OF_WEEK
ORDER BY TOTAL DESC

-----------MOST INCIDENT CATEGORIES BY DAY---------------------
SELECT INCIDENT_CATEGORY, COUNT(INCIDENT_DAY_OF_WEEK) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_DAY_OF_WEEK = 'FRIDAY'
GROUP BY INCIDENT_CATEGORY
ORDER BY TOTAL DESC

SELECT INCIDENT_CATEGORY, COUNT(INCIDENT_DAY_OF_WEEK) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_DAY_OF_WEEK = 'SATURDAY'
GROUP BY INCIDENT_CATEGORY
ORDER BY TOTAL DESC

SELECT INCIDENT_CATEGORY, COUNT(INCIDENT_DAY_OF_WEEK) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_DAY_OF_WEEK = 'SUNDAY'
GROUP BY INCIDENT_CATEGORY
ORDER BY TOTAL DESC

SELECT INCIDENT_CATEGORY, COUNT(INCIDENT_DAY_OF_WEEK) AS TOTAL FROM POLICE_INCIDENTS
WHERE INCIDENT_DAY_OF_WEEK = 'MONDAY'
GROUP BY INCIDENT_CATEGORY
ORDER BY TOTAL DESC





































