SELECT * FROM FACT_TABLE

SELECT * FROM CUSTOMER_DIM

SELECT * FROM ITEM_DIM

SELECT * FROM STORE_DIM

SELECT * FROM TIME_DIM

SELECT * FROM TRANS_DIM

-------JOINING THE TABLES----------
SELECT FACT_TABLE.*, [name], CONTACT_NO, NID, ITEM_NAME,[desc], MAN_COUNTRY, SUPPLIER, DIVISION, DISTRICT, UPAZILA,
       [hour], [day], [week], [month], [quarter], [year], [date], [time], TRANS_TYPE, BANK_NAME

INTO SALES

FROM FACT_TABLE LEFT JOIN 

CUSTOMER_DIM ON FACT_TABLE.COUSTOMER_KEY = CUSTOMER_DIM.COUSTOMER_KEY

LEFT JOIN ITEM_DIM ON FACT_TABLE.ITEM_KEY= ITEM_DIM.ITEM_KEY

LEFT JOIN STORE_DIM ON FACT_TABLE.STORE_KEY = STORE_DIM.STORE_KEY

LEFT JOIN TIME_DIM ON FACT_TABLE.TIME_KEY = TIME_DIM.TIME_KEY

LEFT JOIN TRANS_DIM ON FACT_TABLE.PAYMENT_KEY = TRANS_DIM.PAYMENT_KEY

WHERE TRANS_DIM.PAYMENT_KEY IS NOT NULL AND TIME_DIM.TIME_KEY IS NOT NULL AND STORE_DIM.STORE_KEY IS NOT NULL AND ITEM_DIM.ITEM_KEY IS NOT NULL AND CUSTOMER_DIM.COUSTOMER_KEY IS NOT NULL

------------VIEWING NEW COMBINED FULL TABLE------------

SELECT * FROM SALES

-------TOTALS------------

-------NUMBER NAMES AND CUSTOMERS-------
SELECT COUNT(DISTINCT NAME) AS TOTAL_CUSTOMERS FROM SALES----NAMES OF CUSTOMERS

SELECT COUNT(DISTINCT COUSTOMER_KEY) AS TOTAL_CUSTOMERS FROM SALES----COUSTOMER KEY

SELECT COUNT(DISTINCT CONTACT_NO) AS TOTAL_CUSTOMERS FROM SALES--------CONTACT_NUMBER

SELECT COUNT(DISTINCT NID) AS TOTAL_CUSTOMERS FROM SALES-------NATIONAL ID

------NUMBER OF PAYMENTS AND  METHODS----------
SELECT COUNT(DISTINCT PAYMENT_KEY) AS TOTAL_PAYMENTS FROM SALES---------PAYMENT KEY

SELECT COUNT( DISTINCT TRANS_TYPE) AS TOTAL_PAYMETHODS FROM SALES---------TRANSACTION TYPE

SELECT COUNT( DISTINCT BANK_NAME) AS TOTAL_BANKS FROM SALES--------BANK NAMES

-------NUMBER OF TIMES OF TRANSACTIONS AND TIME DISTRIBUTION----------
SELECT COUNT(DISTINCT TIME_KEY) AS TOTAL_TIMES FROM SALES----------TIME_KEY

SELECT DISTINCT HOUR, COUNT(HOUR) AS TOTAL FROM SALES---------------HOUR
GROUP BY HOUR
ORDER BY TOTAL DESC

SELECT DISTINCT DAY, COUNT(DAY) AS TOTAL FROM SALES ---------------------DAY
GROUP BY DAY
ORDER BY TOTAL DESC


SELECT DISTINCT WEEK, COUNT(WEEK) AS TOTAL FROM SALES --------------WEEK
GROUP BY WEEK
ORDER BY TOTAL DESC

SELECT DISTINCT MONTH, COUNT(MONTH) AS TOTAL FROM SALES--------------MONTH
GROUP BY MONTH
ORDER BY TOTAL DESC

SELECT DISTINCT QUARTER, COUNT(QUARTER) AS TOTAL FROM SALES----------------QUATER
GROUP BY QUARTER
ORDER BY TOTAL DESC

SELECT DISTINCT YEAR, COUNT(YEAR) AS TOTAL FROM SALES----------------YEAR
GROUP BY YEAR
ORDER BY TOTAL DESC

SELECT  COUNT(DISTINCT DATE) AS TOTAL_DATES FROM SALES----------------DATE

SELECT COUNT(DISTINCT TIME) AS TOTAL_TIME FROM SALES----------------TIME

---------ITEMS A AND NUMBER OF ITEMS ORDERED----------------
SELECT COUNT(DISTINCT ITEM_KEY) AS TOTAL_ITEMS FROM SALES---------------------ITEM_KEY

SELECT COUNT(DISTINCT ITEM_NAME) AS TOTAL_ITEMS FROM SALES-----------------------ITEM_NAME

SELECT COUNT(DISTINCT [desc]) AS TOTAL_DESC FROM SALES-----------------------------DESC

SELECT COUNT(DISTINCT SUPPLIER) AS TOTAL_SUPPLIERS FROM SALES--------------------SUPPLIER

SELECT DISTINCT ITEM_KEY, ITEM_NAME, COUNT(ITEM_KEY) AS TOTAL FROM SALES------------------ITEM_KEY AND ITEM NAME
GROUP BY ITEM_KEY, ITEM_NAME
ORDER BY TOTAL DESC

SELECT DISTINCT [desc], COUNT([desc]) AS TOTAL FROM SALES----------------------------------DESC
GROUP BY [desc]
ORDER BY TOTAL DESC

SELECT DISTINCT SUPPLIER, COUNT(SUPPLIER) AS TOTAL FROM SALES----------------------------------DESC
GROUP BY SUPPLIER
ORDER BY TOTAL DESC

-------------NUMBER OF STORES, LOCATIONS AND NUMBER OF ORDERS FROM THEM------------
SELECT COUNT(DISTINCT STORE_KEY) AS TOTAL_STORES FROM SALES-------------------------------STORE_KEY

SELECT DISTINCT STORE_KEY, COUNT(STORE_KEY) AS TOTAL FROM SALES----------------------------------DESC
GROUP BY STORE_KEY
ORDER BY TOTAL DESC

SELECT COUNT(DISTINCT MAN_COUNTRY) AS TOTAL_MAN_COUNTRY FROM SALES--------------------------MANUFACTURING_COUNTRY

SELECT COUNT(DISTINCT DIVISION) AS TOTAL_DIVISIONS FROM SALES-------------------------------DIVISION

SELECT COUNT(DISTINCT DISTRICT) AS TOTAL_DISTRICTS FROM SALES-------------------------------DISTRICTS

SELECT COUNT(DISTINCT UPAZILA) AS TOTAL_UPAZILA FROM SALES----------------------------UPAZILA

SELECT DISTINCT MAN_COUNTRY, COUNT(MAN_COUNTRY) AS TOTAL FROM SALES----------------------------------MAN COUNTRY
GROUP BY MAN_COUNTRY
ORDER BY TOTAL DESC

SELECT DISTINCT DIVISION, COUNT(DIVISION) AS TOTAL FROM SALES----------------------------------DIVISION
GROUP BY DIVISION
ORDER BY TOTAL DESC

SELECT DISTINCT DISTRICT, COUNT(DISTRICT) AS TOTAL FROM SALES----------------------------------DISTRICT
GROUP BY DISTRICT
ORDER BY TOTAL DESC

SELECT DISTINCT UPAZILA, COUNT(UPAZILA) AS TOTAL FROM SALES----------------------------------UPAZILA
GROUP BY UPAZILA
ORDER BY TOTAL DESC

-----------CUSTOMER  XTICS AND OTHER PARAMETERS BY QUANTITY ORDERED------------

SELECT SUM(QUANTITY) AS TOTAL_QUANTITY_OF_GOODS FROM SALES

SELECT AVG(QUANTITY) AS AVG_QUANTITY, MAX(QUANTITY) AS HIGHEST , MIN(QUANTITY) AS LOWEST FROM SALES

------------PAYMENT METHOD AND BANK BY QUANTITY ORDERED---------------------
SELECT DISTINCT PAYMENT_KEY, BANK_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES
GROUP BY PAYMENT_KEY, BANK_NAME
ORDER BY TOTAL_QUANTITY DESC

------------TRANSACTION TYPE BY QUANTITY ORDERED--------------
SELECT DISTINCT TRANS_TYPE, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES
GROUP BY TRANS_TYPE
ORDER BY TOTAL_QUANTITY DESC

------------CUSTOMER AND NAMES BY QUANTITY ORDERED--------------
SELECT DISTINCT COUSTOMER_KEY, NAME, CONTACT_NO, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES
GROUP BY COUSTOMER_KEY, NAME, CONTACT_NO
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT NAME, CONTACT_NO, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES
GROUP BY NAME, CONTACT_NO
ORDER BY TOTAL_QUANTITY DESC

-----------TIME VARIATION WITH QUANTITY-------------
SELECT DISTINCT HOUR, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES-----HOUR
GROUP BY HOUR
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT DAY, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES---------DAY
GROUP BY DAY
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT WEEK, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES---------WEEK
GROUP BY WEEK
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT MONTH, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES---------MONTH
GROUP BY MONTH
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT QUARTER, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES---------QUARTER
GROUP BY QUARTER
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT YEAR, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES---------YEAR
GROUP BY YEAR
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT DATE , SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES---------DATE
GROUP BY DATE
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT TIME, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES---------TIME
GROUP BY TIME
ORDER BY TOTAL_QUANTITY DESC

------------ITEM PROPERTIES VARIATION WITH QUANTITY------------

SELECT DISTINCT ITEM_KEY, ITEM_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES------------------ITEM_KEY AND ITEM NAME
GROUP BY ITEM_KEY, ITEM_NAME
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT [desc], SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES----------------------------------DESCRIPTION
GROUP BY [desc]
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT SUPPLIER, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES----------------------------------SUPPLIER
GROUP BY SUPPLIER
ORDER BY TOTAL_QUANTITY DESC

----------STORES AND CUSTOMER LOCATION VARIATION WITH QUANTITY-----------
SELECT DISTINCT STORE_KEY, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES----------------------------------STORE
GROUP BY STORE_KEY
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT MAN_COUNTRY, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES----------------------------------MANUFACTURING COUNTRY
GROUP BY MAN_COUNTRY
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT DIVISION, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES----------------------------------DIVISION
GROUP BY DIVISION
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT DISTRICT, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES----------------------------------DISTRICT
GROUP BY DISTRICT
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT UPAZILA, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES----------------------------------UPAZILA
GROUP BY UPAZILA
ORDER BY TOTAL_QUANTITY DESC

-------QUANTITY BY UNIT-------------
SELECT DISTINCT UNIT, SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES----------------------------------UNIT
GROUP BY UNIT
ORDER BY TOTAL_QUANTITY DESC

SELECT DISTINCT UNIT, UNIT_PRICE FROM SALES


----------PARAMETRS VARIATION WITH TOTAL_PRICE--------------
SELECT SUM(TOTAL_PRICE) AS GRAN_TOTAL_PRICE_OF_GOODS FROM SALES

SELECT AVG(TOTAL_PRICE) AS AVG_TOTAL_PRICE, MAX(TOTAL_PRICE) AS HIGHEST , MIN(TOTAL_PRICE) AS LOWEST FROM SALES

------------PAYMENT METHOD AND BANK BY TOTAL PRICE SPENT---------------------
SELECT DISTINCT PAYMENT_KEY, BANK_NAME, SUM(TOTAL_PRICE) AS TOTAL FROM SALES
GROUP BY PAYMENT_KEY, BANK_NAME
ORDER BY TOTAL DESC

------------TRANSACTION TYPE BY TOTAL PRICE SPENT--------------
SELECT DISTINCT TRANS_TYPE, SUM(TOTAL_PRICE) AS TOTAL FROM SALES
GROUP BY TRANS_TYPE
ORDER BY TOTAL DESC

------------CUSTOMER AND NAMES BY TOTAL PRICE SPENT--------------
SELECT DISTINCT COUSTOMER_KEY, NAME, CONTACT_NO, SUM(TOTAL_PRICE) AS TOTAL FROM SALES
GROUP BY COUSTOMER_KEY, NAME, CONTACT_NO
ORDER BY TOTAL DESC

SELECT DISTINCT NAME, CONTACT_NO, SUM(TOTAL_PRICE) AS TOTAL FROM SALES
GROUP BY NAME, CONTACT_NO
ORDER BY TOTAL DESC

-----------TIME VARIATION WITH TOTAL PRICE SPENT-------------
SELECT DISTINCT HOUR, SUM(TOTAL_PRICE) AS TOTAL FROM SALES-----HOUR
GROUP BY HOUR
ORDER BY TOTAL DESC

SELECT DISTINCT DAY, SUM(TOTAL_PRICE) AS TOTAL FROM SALES---------DAY
GROUP BY DAY
ORDER BY TOTAL DESC

SELECT DISTINCT WEEK, SUM(TOTAL_PRICE) AS TOTAL FROM SALES---------WEEK
GROUP BY WEEK
ORDER BY TOTAL DESC

SELECT DISTINCT MONTH, SUM(TOTAL_PRICE) AS TOTAL FROM SALES---------MONTH
GROUP BY MONTH
ORDER BY TOTAL DESC

SELECT DISTINCT QUARTER, SUM(TOTAL_PRICE) AS TOTAL FROM SALES---------QUARTER
GROUP BY QUARTER
ORDER BY TOTAL DESC

SELECT DISTINCT YEAR, SUM(TOTAL_PRICE) AS TOTAL FROM SALES---------YEAR
GROUP BY YEAR
ORDER BY TOTAL DESC

SELECT DISTINCT DATE , SUM(TOTAL_PRICE) AS TOTAL FROM SALES---------DATE
GROUP BY DATE
ORDER BY TOTAL DESC

SELECT DISTINCT TIME, SUM(TOTAL_PRICE) AS TOTAL FROM SALES---------TIME
GROUP BY TIME
ORDER BY TOTAL DESC

------------ITEM PROPERTIES VARIATION WITH TOTAL PRICE------------

SELECT DISTINCT ITEM_KEY, ITEM_NAME, SUM(TOTAL_PRICE) AS TOTAL FROM SALES------------------ITEM_KEY AND ITEM NAME
GROUP BY ITEM_KEY, ITEM_NAME
ORDER BY TOTAL DESC

SELECT DISTINCT [desc], SUM(TOTAL_PRICE) AS TOTAL FROM SALES----------------------------------DESCRIPTION
GROUP BY [desc]
ORDER BY TOTAL DESC

SELECT DISTINCT SUPPLIER, SUM(TOTAL_PRICE) AS TOTAL FROM SALES----------------------------------SUPPLIER
GROUP BY SUPPLIER
ORDER BY TOTAL DESC

----------STORES AND CUSTOMER LOCATION VARIATION WITH TOTAL PRICE-----------
SELECT DISTINCT STORE_KEY, SUM(TOTAL_PRICE) AS TOTAL FROM SALES----------------------------------STORE
GROUP BY STORE_KEY
ORDER BY TOTAL DESC

SELECT DISTINCT MAN_COUNTRY, SUM(TOTAL_PRICE) AS TOTAL FROM SALES----------------------------------MANUFACTURING COUNTRY
GROUP BY MAN_COUNTRY
ORDER BY TOTAL DESC

SELECT DISTINCT DIVISION, SUM(TOTAL_PRICE) AS TOTAL FROM SALES----------------------------------DIVISION
GROUP BY DIVISION
ORDER BY TOTAL DESC

SELECT DISTINCT DISTRICT, SUM(TOTAL_PRICE) AS TOTAL FROM SALES----------------------------------DISTRICT
GROUP BY DISTRICT
ORDER BY TOTAL DESC

SELECT DISTINCT UPAZILA, SUM(TOTAL_PRICE) AS TOTAL FROM SALES----------------------------------UPAZILA
GROUP BY UPAZILA
ORDER BY TOTAL DESC

-------TOTAL_PRICE BY UNIT-------------
SELECT DISTINCT UNIT, SUM(TOTAL_PRICE) AS TOTAL FROM SALES----------------------------------UNIT
GROUP BY UNIT
ORDER BY TOTAL DESC

SELECT DISTINCT UNIT, UNIT_PRICE FROM SALES

--------AVERAGE QUANTITY AND PRICE FOR MANUFACTURED GOODS IN BANGLADESH, INDIA AND THE UNITED STATES
SELECT MAN_COUNTRY, AVG(QUANTITY) AS AVG_QUANTITY FROM SALES
GROUP BY MAN_COUNTRY
ORDER BY AVG_QUANTITY DESC

SELECT MAN_COUNTRY, AVG(TOTAL_PRICE) AS AVG_PRICE FROM SALES
GROUP BY MAN_COUNTRY
ORDER BY AVG_PRICE DESC

------- QUANTITY TOTAL PRICE MADE BY SUPPLIERS BY YEARS
SELECT SUPPLIER,YEAR, SUM(QUANTITY) AS TOTAL FROM SALES
WHERE YEAR = '2016'
GROUP BY SUPPLIER, YEAR
ORDER BY TOTAL DESC

SELECT SUPPLIER,YEAR, SUM(TOTAL_PRICE) AS TOTAL FROM SALES
WHERE YEAR = '2014'
GROUP BY SUPPLIER, YEAR
ORDER BY TOTAL DESC

------CUSTOMER NAMES THAT MEET A CERTAIN CATEGORY------------
SELECT NAME, SUM(TOTAL_PRICE) AS TOTAL FROM SALES
WHERE TOTAL_PRICE > 100
GROUP BY NAME
ORDER BY TOTAL DESC

SELECT NAME, SUM(QUANTITY) AS TOTAL FROM SALES
WHERE QUANTITY < 3
GROUP BY NAME
ORDER BY TOTAL DESC

---------SUBQUERIES-------------
SELECT * FROM SALES

SELECT *
FROM SALES
WHERE ITEM_NAME IN(
                  SELECT DISTINCT ITEM_NAME
			      FROM SALES
			      WHERE SUPPLIER LIKE 'BIGSO AB');

SELECT * FROM SALES
WHERE YEAR BETWEEN '2014' AND '2018'

SELECT QUANTITY
         FROM SALES
         WHERE NAME IN (SELECT DISTINCT NAME
                            FROM SALES
                            WHERE YEAR BETWEEN '2016' AND '2018')