SELECT * FROM SSUSA

-------TOP SHOOTING INCIDENTS(VICTIMS)-------
SELECT STATE, INCIDENT_DATE, ADDRESS, CITY_OR_COUNTY, SUM(VICTIMS_KILLED) AS KILL_TOTAL, SUM(VICTIMS_INJURED) AS INJURED_VICTIMS FROM SSUSA
GROUP BY STATE, INCIDENT_DATE, ADDRESS, CITY_OR_COUNTY
ORDER BY KILL_TOTAL DESC, INJURED_VICTIMS 

SELECT SUM(VICTIMS_KILLED) AS KILL_TOTAL, SUM(VICTIMS_INJURED) AS INJURED_TOTAL FROM SSUSA

SELECT MIN(INCIDENT_DATE) AS START_DATE, MAX(INCIDENT_DATE) AS END_DATE FROM SSUSA

---------TOP SHOOTINGS(SUSPECTS)----------
SELECT STATE, INCIDENT_DATE, ADDRESS, CITY_OR_COUNTY, SUM(CAST(SUSPECTS_KILLED AS INT)) AS KILL_TOTAL, SUM(SUSPECTS_INJURED) AS INJURED_SUSPECTS, SUM(SUSPECTS_ARRESTED) AS TOTAL_ARRESTS FROM SSUSA
GROUP BY STATE, INCIDENT_DATE, ADDRESS, CITY_OR_COUNTY
ORDER BY KILL_TOTAL , INJURED_SUSPECTS, TOTAL_ARRESTS DESC

SELECT SUM(CAST(SUSPECTS_KILLED AS INT)) AS KILL_TOTAL, SUM(SUSPECTS_INJURED) AS INJURED_SUSPECTS, SUM(SUSPECTS_ARRESTED) AS TOTAL_ARRESTS FROM SSUSA

---------MOST VIOLENT STATES-----------
SELECT STATE, SUM(VICTIMS_KILLED) AS KILL_TOTAL, SUM(SUSPECTS_ARRESTED) AS ARREST_TOTAL FROM SSUSA
GROUP BY STATE
ORDER BY KILL_TOTAL DESC, ARREST_TOTAL

SELECT STATE, COUNT(DISTINCT INCIDENT_ID) AS TOTAL_INCIDENTS FROM SSUSA
GROUP BY STATE
ORDER BY TOTAL_INCIDENTS DESC

SELECT COUNT( DISTINCT INCIDENT_ID) AS TOTAL_INCIDENTS FROM SSUSA

-------MOST VOILENT DAYS----------
SELECT INCIDENT_DATE, COUNT( DISTINCT INCIDENT_ID) AS TOTAL_INCIDENTS FROM SSUSA
GROUP BY  INCIDENT_DATE
ORDER BY TOTAL_INCIDENTS DESC

---TOP--BABY---NAMES--IN--THE UNITED STATES--------

SELECT * FROM BABY

----TOP  AND LEAST YEARS AND NUMBER OF NAMES GIVEN---
SELECT YEAR, SUM(OCCURENCES) AS TOTAL, COUNT(DISTINCT TOP_NAME) AS NAME_NUMBER FROM BABY
GROUP BY  YEAR
ORDER BY TOTAL DESC, NAME_NUMBER

SELECT YEAR, SUM(OCCURENCES) AS TOTAL, COUNT(DISTINCT TOP_NAME) AS NAME_NUMBER FROM BABY
GROUP BY  YEAR
ORDER BY TOTAL ASC, NAME_NUMBER

------TOP GIVEN NAME AND ITS GENDER EVER--------
SELECT TOP(10) TOP_NAME, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
GROUP BY TOP_NAME, GENDER
ORDER BY TOTAL DESC

------LEAST GIVEN NAME AND IT'S GENDER EVER--------
SELECT TOP(10) TOP_NAME, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
GROUP BY  TOP_NAME, GENDER
ORDER BY TOTAL ASC


----TOP NAMES GIVEN IN EACH STATE EVER---------
SELECT TOP(10) TOP_NAME, STATE, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
GROUP BY TOP_NAME, STATE, GENDER
ORDER BY TOTAL DESC

------LEAST GIVEN NAME IN A STATE EVER--------
SELECT TOP(10) TOP_NAME, STATE, GENDER,  SUM(OCCURENCES) AS TOTAL FROM BABY
GROUP BY TOP_NAME, STATE, GENDER
ORDER BY TOTAL ASC

------MOST GIVEN NAME BY YEAR-----
SELECT TOP(10) TOP_NAME, YEAR, GENDER,  SUM(OCCURENCES) AS TOTAL FROM BABY
GROUP BY TOP_NAME,YEAR, GENDER
ORDER BY TOTAL DESC

------LEAST GIVEN NAME BY YEAR-----
SELECT TOP(10) TOP_NAME, YEAR, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
GROUP BY TOP_NAME, YEAR, GENDER
ORDER BY TOTAL ASC

------GENDER DISTRIBUTION-------

------MOST GIVEN AND LEAST GIVEN MALE NAMES EVER-----
SELECT TOP(10) TOP_NAME, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE GENDER = 'M'
GROUP BY TOP_NAME
ORDER BY TOTAL DESC

SELECT TOP(10) TOP_NAME, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE GENDER = 'M'
GROUP BY TOP_NAME
ORDER BY TOTAL ASC


-----MOST GIVEN AND LEAST GIVEN MALE NAMES BY STATE EVER-------
SELECT TOP(10) TOP_NAME, STATE,  SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE GENDER = 'M'
GROUP BY TOP_NAME, STATE
ORDER BY TOTAL DESC

SELECT TOP(10) TOP_NAME, STATE,  SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE GENDER = 'M'
GROUP BY TOP_NAME, STATE
ORDER BY TOTAL ASC

-----MOST GIVEN AND LEAST GIVEN FEMALE NAMES EVER---------
SELECT TOP(10) TOP_NAME, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE GENDER = 'F'
GROUP BY TOP_NAME
ORDER BY TOTAL DESC

SELECT TOP(10) TOP_NAME, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE GENDER = 'F'
GROUP BY TOP_NAME
ORDER BY TOTAL ASC

----MOST AND LEAST GIVEN FEMALE NAME BY STATE EVER--------
SELECT TOP(10) TOP_NAME, STATE,  SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE GENDER = 'F'
GROUP BY TOP_NAME, STATE
ORDER BY TOTAL DESC

SELECT TOP(10) TOP_NAME, STATE,  SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE GENDER = 'F'
GROUP BY TOP_NAME, STATE
ORDER BY TOTAL ASC

---------TOP AND BOTTOM NAMES IN SELECT YEARS-------

SELECT MIN(YEAR) AS START_YEAR, MAX(YEAR) AS END_YEAR FROM BABY

------------YEAR 1910----------
SELECT TOP_NAME, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE YEAR = 1910
GROUP BY TOP_NAME, GENDER
ORDER BY TOTAL DESC

SELECT TOP_NAME, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE YEAR = 1910
GROUP BY TOP_NAME, GENDER
ORDER BY TOTAL ASC

------------YEAR 1950-----------
SELECT TOP_NAME, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE YEAR = 1950
GROUP BY TOP_NAME, GENDER
ORDER BY TOTAL DESC

SELECT TOP_NAME, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE YEAR = 1950
GROUP BY TOP_NAME, GENDER
ORDER BY TOTAL ASC

----------YEAR 2000---------
SELECT TOP_NAME, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE YEAR = 2000
GROUP BY TOP_NAME, GENDER
ORDER BY TOTAL DESC

SELECT TOP_NAME, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE YEAR = 2000
GROUP BY TOP_NAME, GENDER
ORDER BY TOTAL ASC

---------YEAR 2012--------
SELECT TOP_NAME, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE YEAR = 2012
GROUP BY TOP_NAME, GENDER
ORDER BY TOTAL DESC

SELECT TOP_NAME, GENDER, SUM(OCCURENCES) AS TOTAL FROM BABY
WHERE YEAR = 2012
GROUP BY TOP_NAME, GENDER
ORDER BY TOTAL ASC




